export const DEFAULT_READ_CAPACITY = 5
export const DEFAULT_WRITE_CAPACITY = 5
export const DEFAULT_AUTOSCALING_MIN_CAPACITY = 5
export const DEFAULT_AUTOSCALING_MAX_CAPACITY = 500
export const DEFAULT_AUTOSCALING_TARGET_UTILIZATION = 70
