export { BatchGet } from './batch-get'
export { BatchWrite } from './batch-write'
export { default as Config } from './config'
export * as Connection from './connections'
export * as $ from './decorator' // export decorators prefixed with $ for convenience
export * as Decorator from './decorator'
export { Attribute } from './decorator'
export { DocumentClient as $DocumentClient } from './decorator/document-client'
export { GlobalSecondaryIndex as $GlobalSecondaryIndex, type GlobalSecondaryIndexOptions } from './decorator/global-secondary-index'
export { LocalSecondaryIndex as $LocalSecondaryIndex } from './decorator/local-secondary-index'
export { PrimaryKey as $PrimaryKey } from './decorator/primary-key'
export { Table as $Table } from './decorator/table'
export { DocumentClient } from './document-client'
export { DynamoAttributeType } from './dynamo-attribute-types'
export * as Errors from './errors'
export * as Events from './events'
export * as Metadata from './metadata'
export * as Query from './query'
export type { ITable } from './table'
export { Table } from './table'
export { AttributeType } from './tables/attribute-type'
export { Transaction } from './transaction'
